FROM httpd:2.4.41
RUN apt-get update && apt-get install -y \
    libapache2-mod-wsgi  \
	curl \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    python3-pip \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install Flask

COPY ./html/ /usr/local/apache2/htdocs/
