"""empty message

Revision ID: 2e211d7a8cfa
Revises: 5bb6f602b35d
Create Date: 2019-10-22 05:40:48.453398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e211d7a8cfa'
down_revision = '5bb6f602b35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_type')
    # ### end Alembic commands ###
